# Generated by Django 5.1.5 on 2025-02-16 22:29

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PizzaCheese',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cheese', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='PizzaCrust',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crust', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='PizzaSauce',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sauce', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='PizzaSizes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='PizzaToppings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('top', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=200)),
                ('cardNo', models.CharField(help_text='Enter 16 digit card number. No spaces!', max_length=16, validators=[django.core.validators.MinLengthValidator(16), django.core.validators.MaxLengthValidator(16), django.core.validators.RegexValidator('^\\d{16}$', 'Enter a valid 16-digit card number')])),
                ('ExpiryMonth', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10), (11, 11)], default=1)),
                ('ExpiryYear', models.IntegerField(choices=[(2025, 2025), (2026, 2026), (2027, 2027), (2028, 2028), (2029, 2029), (2030, 2030), (2031, 2031), (2032, 2032), (2033, 2033), (2034, 2034), (2035, 2035), (2036, 2036), (2037, 2037), (2038, 2038), (2039, 2039), (2040, 2040), (2041, 2041), (2042, 2042), (2043, 2043), (2044, 2044), (2045, 2045), (2046, 2046), (2047, 2047), (2048, 2048), (2049, 2049)], default=2025)),
                ('cvv', models.CharField(help_text='Enter the 3 digit CVV at the back of your card', max_length=3, validators=[django.core.validators.MinLengthValidator(3), django.core.validators.MaxLengthValidator(3), django.core.validators.RegexValidator('^\\d{3}$', 'Enter a valid 3-digit CVV')])),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Pizza',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pizzas', to=settings.AUTH_USER_MODEL)),
                ('cheese', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Pizza.pizzacheese')),
                ('crust', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Pizza.pizzacrust')),
                ('sauce', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Pizza.pizzasauce')),
                ('size', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Pizza.pizzasizes')),
                ('toppings', models.ManyToManyField(blank=True, to='Pizza.pizzatoppings')),
            ],
        ),
        migrations.CreateModel(
            name='Confirm_Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('delivery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Pizza.delivery')),
                ('pizza', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Pizza.pizza')),
            ],
        ),
    ]
