# Generated by Django 5.1.5 on 2025-02-16 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pizza', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pizza',
            name='toppings',
            field=models.ManyToManyField(blank=True, to='Pizza.pizzatoppings'),
        ),
    ]
