# Generated by Django 5.1.5 on 2025-02-17 00:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Pizza', '0002_alter_confirm_order_delivery_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='confirm_order',
            old_name='create_time',
            new_name='created_at',
        ),
    ]
